### PR TITLE
Gemify, yo

### PR DESCRIPTION
**Pull request by steveklabnik**
I think that `grailbird` is a better name than `grailbird_updater`, so I made it that.

Anyway, you can now use this as a gem. `rake release` will build and release a `0.0.1`.

:heart: :heart: :heart:

### CODE REVIEW

**Comment by steveklabnik** [comment]
Oh and you need an account on rubygems.org first.

**Comment by steveklabnik** [comment]
Oh, I forgot a description. One moment.

**Comment by DeMarko** [comment]
Ah, grailbird_updater was chosen intentionally as I believe Twitter's cold storage retriever is called Grailbird

**Comment by steveklabnik** [comment]
Oh neat! that's right. I'll fix that too then.

**Comment by DeMarko** [comment]
Thank You

amidoinGitHubrite?

**Comment by steveklabnik** [comment]
I think so. :metal:

**Comment by steveklabnik** [comment]
that almost came out as :meat_on_bone:

**Comment by DeMarko** [comment]
HAMBONE.ico

**Pull request merged**
