### PR TITLE
Running tests requires minitest

### PR DESCRIPTION
**Pull request by theevocater**
I'm not sure if this is a thing you do, but I ran into it when messing around. You use minitest for tests, but don't include it in the Gemfile. Sorry if its just practice not to.

### CODE REVIEW

**Comment by DeMarko** [comment]
I think @steveklabnik added the minitest stuff but I never got around to writing tests for this.

**Comment by steveklabnik** [comment]
Minitest is included with Ruby as of Ruby 1.9, so this is only needed if you plan on supporting Ruby 1.8, @DeMarko.

**Comment by DeMarko** [comment]
ohhhh. hmm, @theevocater, I really wasn't planning on supporting 1.8, YOLO

**Comment by DeMarko** [comment]
I mean, whatever. It can just...go there?

**Comment by steveklabnik** [comment]
It won't hurt anything. It's 100% neutral in its current form; if you wanted to use a newer version of MiniTest than the one that's bundled with Ruby, you could specify it there, but just by itself is basically a noop.

**Comment by DeMarko** [comment]
ah, alright. NOOP NOOP

**Pull request merged**
